language: php
services:
  - mariadb
php:
  - 7.3
addons:
  mariadb: '10.4'
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  npm: true
  directories:
    - ~/.cache
    - $HOME/.composer/cache/files
install:
  - make install
script:
  - make test
env:
  - DATABASE_URL=mysql://root:@127.0.0.1:3306/contact_test
